exp_name: 'BPT-open-8k-8-16'
logdir: '/path/to/log'

# condition
conditioned_on_pc: True
encoder_name: miche-256-feature
encoder_freeze: False
pc_num: 4096

# representation config
use_special_block: True
block_compression: True
block_size: 8
offset_size: 16
quant_bit: 7

# architecture
mode: 'vertices'
dim: 1024
depth: 24
dropout: 0.0
max_seq_len: 10000